# Site settings
title: Paul Y. Wang
description: My Data Science Profolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
url: "https://pywang128.github.io/"

# User settings
username: Paul Y. Wang
user_description: An aspiring data scientist, passionate about data-driven solutions and machine learning model to deliver valuable insights.<br><br>Demonstrated ability in regression, classification, and clustering on data sets, as well as natural language processing, sentiment analysis, and develop a recommendation system. Determined to continually learn, improve and open-minded to new opportunities for growth.

user_title: Aspiring Data Scientist
email: pywang128@gmail.com
#twitter_username: lorem_ipsum
github_username: pywang128
#gplus_username: lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
